=head1 DESCRIPTION

The B<FTimesCat> utility reads the contents of a file or stdin and
writes them to stdout.  The specified filename is assumed to be
encoded (i.e., neutered by FTimes), and it is automatically decoded to
obtain the real name, which may contain special characters.  For
WINX platforms, the decoded name is assumed to be a UTF-8 string.

