=pod

=head1 NAME

ftimes-dbm-weed - Delete records from a Berkeley database

=head1 SYNOPSIS

B<ftimes-dbm-weed> B<[-o option[,option[,...]]]> B<-d db> B<-f {file|-}>

=head1 DESCRIPTION

This utility deletes specified records from a database that has been
created with ftimes-dbm-make(1).  Input is expected to be plain text
with one key per line.

=head1 OPTIONS

=over 4

=item B<-d db>

Specifies the name of the database to weed.

=item B<-f {file|-}>

Specifies the name of the input file.  A value of '-' will cause the
program to read from stdin.

=item B<-o option,[option[,...]]>

Specifies the list of options to apply.  Currently the following
options are supported:

=over 4

=item BeQuiet

Don't report errors (i.e., be quiet) while processing files.

=back

=back

=head1 AUTHOR

Klayton Monroe

=head1 SEE ALSO

ftimes-dbm-dump(1), ftimes-dbm-make(1)

=head1 LICENSE

All documentation and code are distributed under same terms and
conditions as FTimes.

=cut
