=head1 RETURN VALUES

Upon successful completion, a value of B<XER_OK> (0) is returned.
If the program encountered a critical error and had to abort
immediately, the value B<XER_Abort> (1) is returned.  If the command
line does not conform to the required syntax, a value of B<XER_Usage>
(2) is returned.  Otherwise, one of the following error codes is
returned.  These codes indicate which subsystem encountered the
fatal error.

=over 5

=item *

B<XER_BootStrap> (3)

=item *

B<XER_ProcessArguments> (4)

=item *

B<XER_Initialize> (5)

=item *

B<XER_CheckDependencies> (6)

=item *

B<XER_Finalize> (7)

=item *

B<XER_WorkHorse> (8)

=item *

B<XER_FinishUp> (9)

=item *

B<XER_FinalStage> (10)

=back

