=head1 EXAMPLES

=head2 Example 1. Normal Operation

This example demonstrates how to remove files whose attributes match
values specified in an B<FTimes> snapshot called 'snapshot.map'.

Assume that the snapshot contains the following records:

    --- snapshot.map ---
    name|size|md5|sha1
    "/tmp/foo"|5|aba0f47afec9a5d52812ace09d226641|74a39bb962c5f40b0c6ab1db1704405d33814b50
    "/tmp/bar"|5|fe3fe3cd810a420a0d0be3be535d1c3e|d3e67cc9b12f89555a62e56149ca5db3fa80fb8a
    "/tmp/com"|5|1cf92b09e67425473e9432657cca85bf|fb044d1d79299e9ff2dbf78dabc3e811cd49dd3a
    --- snapshot.map ---

Suppose you wish to remove all files whose size and MD5 hash match
the values found in the snapshot.  The commands presented below
provide equivalent ways to achieve that end goal:

    ftimes-srm -m none+size+md5 snapshot.map
or
    ftimes-srm -m all-hashes+md5 snapshot.map
or
    ftimes-srm -m all-sha1-sha256 snapshot.map
or
    ftimes-xformer -f snapshot.map -L name,size,md5 | ftimes-srm -m none+size+md5 -

If you wanted to take a more cautious approach, you could try a
dry run simply by adding the B<--dry-run> (or B<-n>) option like so:

    ftimes-srm -m none+size+md5 --dry-run snapshot.map

